[package]
name = "edgetpu-driver"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
cpp = "0.5.9"

[build-dependencies]
bindgen = "0.69.4"
vcpkg = "0.2.15"

[features]
max-freq = []
