[package]
name = "libedgetpu"
version = "0.1.0"
edition = "2021"
build = "build/build.rs"

[dependencies]
cpp = "0.5.9"
thiserror = "1.0.63"

[build-dependencies]
cpp_build = "0.5.9"
flatbuffers = "24.3.25"

[features]
max-freq = []

[dev-dependencies]
image = "0.25.1"
